# Built the command using a golang base image.
FROM golang:1.20 AS build
ADD . /go/src/github.com/m-lab/access
WORKDIR /go/src/github.com/m-lab/access
RUN CGO_ENABLED=0 go install -v ./cmd/envelope

# Now copy the resulting command into the minimal base image.
FROM alpine:3.14
COPY --from=build /go/bin/envelope /
WORKDIR /
RUN apk add --no-cache iptables ip6tables ca-certificates && update-ca-certificates
ENTRYPOINT ["/envelope"]
