# Built the command using a golang base image.
FROM golang:1.14.4-alpine3.12 AS build
RUN apk add git
ADD . /go/src/github.com/m-lab/access
RUN go get -v github.com/m-lab/access/cmd/envelope

# Now copy the resulting command into the minimal base image.
FROM alpine:3.12
COPY --from=build /go/bin/envelope /
WORKDIR /
RUN apk add --no-cache iptables ip6tables ca-certificates && update-ca-certificates
ENTRYPOINT ["/envelope"]
